version: "3.8"

services:
  api:
    build:
      dockerfile: build/docker/api/Dockerfile
      context: ./
    image: search-api:latest
    ports:
      - "8000:8000"

  ui:
    build:
      dockerfile: build/docker/ui/Dockerfile
      context: ./
    image: search-ui:latest
    ports:
      - "8501:8501"
    environment:
      - API_BASE_URL=http://api:8000
    depends_on:
      - api
